version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: sh -c "python migration_script.py && python manage.py runserver 0.0.0.0:443"
    volumes:
      - .:/code
    ports:
      - "443:443"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SQL_HOST=db
    depends_on:
      - db
      