# Generated by Django 4.1.7 on 2023-04-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='doi',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='link_lattes',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='autor',
            name='resumo',
            field=models.TextField(blank=True),
        ),
    ]
