# Generated by Django 4.1.7 on 2023-04-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_alter_artigo_doi_alter_autor_link_lattes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='resumo',
            field=models.TextField(blank=True),
        ),
    ]
