# Generated by Django 4.1.7 on 2024-04-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0004_alter_rede_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rede',
            name='arquivo',
            field=models.FileField(upload_to='redes/%Y%m%d'),
        ),
    ]
