# Generated by Django 4.1.7 on 2024-05-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0005_alter_rede_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rede',
            name='arquivo',
            field=models.FileField(upload_to='redes/%Y/%m/%d'),
        ),
    ]
